
name = "craig-ai"
account_id = "1e6412807f33d56a62217477e87196d2"
compatibility_date = "2025-12-11"

pages_build_output_dir = "dist"

[[vectorize]]
binding = "VECTORIZER"
index_name = "craig-knowledge"
remote = true